# Generated by Django 3.1.1 on 2021-06-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона:')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес:')),
            ],
        ),
    ]
