# Generated by Django 3.1.1 on 2020-10-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_fuschia_violet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuschia',
            name='sort',
        ),
        migrations.AlterField(
            model_name='fuschia',
            name='place',
            field=models.CharField(max_length=255, verbose_name='Размещение в квартире:'),
        ),
    ]
