# Generated by Django 3.1.1 on 2020-10-16 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20201016_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='for_anon_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='in_order',
            field=models.BooleanField(default=False),
        ),
    ]
