# Generated by Django 3.1.1 on 2020-11-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20201025_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='fuchsia',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='fuchsia',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='fuchsia',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='gloxinia',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='gloxinia',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='gloxinia',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='rose',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='rose',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='rose',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='violet',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='violet',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='violet',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Стоимость'),
        ),
    ]
