# Generated by Django 3.1.2 on 2020-11-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20201103_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuchsia',
            name='specie',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вид растения'),
        ),
        migrations.AddField(
            model_name='gloxinia',
            name='specie',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вид растения'),
        ),
        migrations.AddField(
            model_name='rose',
            name='specie',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вид растения'),
        ),
        migrations.AddField(
            model_name='violet',
            name='specie',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вид растения'),
        ),
    ]
