# Generated by Django 3.1.2 on 2020-11-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20201105_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuchsia',
            name='specie',
        ),
        migrations.RemoveField(
            model_name='gloxinia',
            name='specie',
        ),
        migrations.RemoveField(
            model_name='rose',
            name='specie',
        ),
        migrations.RemoveField(
            model_name='violet',
            name='specie',
        ),
        migrations.AlterField(
            model_name='fuchsia',
            name='color',
            field=models.CharField(blank=True, default='Красная', max_length=255, null=True, verbose_name='Окраска цветка:'),
        ),
        migrations.AlterField(
            model_name='fuchsia',
            name='complectation',
            field=models.CharField(blank=True, default='Укорененный черенок', max_length=255, null=True, verbose_name='Комплектация:'),
        ),
        migrations.AlterField(
            model_name='fuchsia',
            name='place',
            field=models.CharField(blank=True, default='Тень', max_length=255, null=True, verbose_name='Размещение в квартире:'),
        ),
        migrations.AlterField(
            model_name='fuchsia',
            name='season',
            field=models.CharField(blank=True, default='Весна', max_length=255, null=True, verbose_name='Сезон цветения:'),
        ),
        migrations.AlterField(
            model_name='gloxinia',
            name='color',
            field=models.CharField(blank=True, default='Красная', max_length=255, null=True, verbose_name='Окраска цветка:'),
        ),
        migrations.AlterField(
            model_name='gloxinia',
            name='complectation',
            field=models.CharField(blank=True, default='Укорененный черенок', max_length=255, null=True, verbose_name='Комплектация:'),
        ),
        migrations.AlterField(
            model_name='gloxinia',
            name='place',
            field=models.CharField(blank=True, default='Тень', max_length=255, null=True, verbose_name='Размещение в квартире:'),
        ),
        migrations.AlterField(
            model_name='gloxinia',
            name='season',
            field=models.CharField(blank=True, default='Весна', max_length=255, null=True, verbose_name='Сезон цветения:'),
        ),
        migrations.AlterField(
            model_name='rose',
            name='color',
            field=models.CharField(blank=True, default='Красная', max_length=255, null=True, verbose_name='Окраска цветка:'),
        ),
        migrations.AlterField(
            model_name='rose',
            name='complectation',
            field=models.CharField(blank=True, default='Укорененный черенок', max_length=255, null=True, verbose_name='Комплектация:'),
        ),
        migrations.AlterField(
            model_name='rose',
            name='place',
            field=models.CharField(blank=True, default='Тень', max_length=255, null=True, verbose_name='Размещение в квартире:'),
        ),
        migrations.AlterField(
            model_name='rose',
            name='season',
            field=models.CharField(blank=True, default='Весна', max_length=255, null=True, verbose_name='Сезон цветения:'),
        ),
        migrations.AlterField(
            model_name='violet',
            name='color',
            field=models.CharField(blank=True, default='Красная', max_length=255, null=True, verbose_name='Окраска цветка:'),
        ),
        migrations.AlterField(
            model_name='violet',
            name='complectation',
            field=models.CharField(blank=True, default='Укорененный черенок', max_length=255, null=True, verbose_name='Комплектация:'),
        ),
        migrations.AlterField(
            model_name='violet',
            name='place',
            field=models.CharField(blank=True, default='Тень', max_length=255, null=True, verbose_name='Размещение в квартире:'),
        ),
        migrations.AlterField(
            model_name='violet',
            name='season',
            field=models.CharField(blank=True, default='Весна', max_length=255, null=True, verbose_name='Сезон цветения:'),
        ),
    ]
