# Generated by Django 3.1.2 on 2020-11-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20201105_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuchsia',
            name='specie',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='gloxinia',
            name='specie',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='rose',
            name='specie',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='violet',
            name='specie',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование'),
        ),
    ]
