# Generated by Django 3.1.1 on 2021-03-06 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20210304_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specie',
        ),
    ]
